- name: Add github.com to known hosts
  ansible.builtin.shell:
    cmd: |
      touch ~/.ssh/known_hosts && cat ~/.ssh/known_hosts && [ grep -q github.com ] || echo "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl" >> ~/.ssh/known_hosts && echo "github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=" >> ~/.ssh/known_hosts && echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=" >> ~/.ssh/known_hosts

- name: Ensure that PycharmProjects directory exists
  ansible.builtin.shell:
    cmd: |
      mkdir -p ~/PycharmProjects

- name: Clone repositories from github lingua-sytes
  ansible.builtin.shell:
    cmd: |
      [ -e ~/PycharmProjects/lingua-sytes ] || ( cp /mnt/samba-data/system_installation/ssh_keys/github_ssh_key ~/github_key_tmp && chmod 600 ~/github_key_tmp && eval `ssh-agent -s` && ssh-add ~/github_key_tmp && ssh-add -L && cd ~/PycharmProjects && git clone git@github.com:lchmielowski/lingua-sytes.git )

- name: Clone repositories from github chassis
  ansible.builtin.shell:
    cmd: |
      [ -e ~/PycharmProjects/chassis ] || ( cp /mnt/samba-data/system_installation/ssh_keys/github_ssh_key ~/github_key_tmp && chmod 600 ~/github_key_tmp && eval `ssh-agent -s` && ssh-add ~/github_key_tmp && ssh-add -L && cd ~/PycharmProjects && git clone git@github.com:lchmielowski/chassis.git )

- name: Clone repositories from github greenhouse
  ansible.builtin.shell:
    cmd: |
      [ -e ~/PycharmProjects/greenhouse ] || ( cp /mnt/samba-data/system_installation/ssh_keys/github_ssh_key ~/github_key_tmp && chmod 600 ~/github_key_tmp && eval `ssh-agent -s` && ssh-add ~/github_key_tmp && ssh-add -L && cd ~/PycharmProjects && git clone git@github.com:lchmielowski/greenhouse.git )

- name: Clone repositories from github ansible-workstations
  ansible.builtin.shell:
    cmd: |
      [ -e ~/PycharmProjects/ansible-workstations ] || ( cp /mnt/samba-data/system_installation/ssh_keys/github_ssh_key ~/github_key_tmp && chmod 600 ~/github_key_tmp && eval `ssh-agent -s` && ssh-add ~/github_key_tmp && ssh-add -L && cd ~/PycharmProjects && git clone git@github.com:lchmielowski/ansible-workstations.git )
